### ISSUE TITLE
Feature Request: Recently starred repos

### ISSUE THREAD

**Issue by markphelps** [muesli/markscribe#14]
👋🏻 great project! 

It would be cool to show something like '_Repos I find interesting_' on my README, perhaps using the [user starredRepos connection?](https://docs.github.com/en/free-pro-team@latest/graphql/reference/objects#starredrepositoryconnection)

**Comment by wtait1** [comment]
FYI I've forked the repo to start working on this feature because I too think it'd be a great addition 🚀
