### ISSUE TITLE
Activity from other apps

### ISSUE THREAD

**Issue by louis030195** [muesli/markscribe#15]
Hello, awesome action !

I'm wondering if it would be possible to implement something for linking automatically my latest Medium posts, or other things (currently reading books on Goodreads ...) probably query-able by API (or scrapping) ?

If you guide me I could implement it.

Thanks !

**Comment by louis030195** [comment]
Actually I didn't see the RSS thing, I tried with Medium it's decent https://github.com/louis030195/louis030195
https://help.medium.com/hc/en-us/articles/214874118-Using-RSS-feeds-of-profiles-and-publications
The URL is ugly though, could put the link on the title.

**Comment by muesli** [comment]
Nice one @louis030195! Btw, if you use `{{- end}}` you can prevent the newlines between your items.

**Comment by muesli** [comment]
Feel free to open individual tickets for specific APIs you think we could/should support. Closing this generic one.
