### ISSUE TITLE
failing at parsing a rss feed

### ISSUE THREAD

**Issue by arthurlogilab** [muesli/markscribe#21]
I'm getting the following error : 

```
Can't render template: template: tpl:33:8: executing "tpl" at <rss "https://arthur.pages.logilab.fr/blog/feed.xml" 2>: error calling rss: runtime error: invalid memory address or nil pointer dereference
```

Running feed validator https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Farthur.pages.logilab.fr%2Fblog%2Ffeed.xml#l85  says the feed is valid (with some warnings)

**Comment by KevinGimbel** [comment]
I'm having the same issue with my feed, it's valid according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkevingimbel.de%2Ffeed.xml

but I get the following error
```
Can't render template: template: tpl:27:17: executing "tpl" at <rss "https://kevingimbel.de/feed.xml" 5>: error calling rss: runtime error: invalid memory address or nil pointer dereference
```

**Comment by muesli** [comment]
This was fixed upstream in `gofeed` and I've just bumped the dependency in markscribe. Will release a `v0.4.0` with that change later today.

**Comment by Melvinvmegen** [comment]
I'm also having this issue with my feed, while it's valid according to: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.melvinvmegen.com%2Frss.xml

`Can't render template: template: tpl:7:8: executing "tpl" at <rss "https://blog.melvinvmegen.com/rss.xml" 10>: error calling rss: runtime error: invalid memory address or nil pointer dereference`

I am missing something?
