### ISSUE TITLE
[Question] This overrides my current README file?

### ISSUE THREAD

**Issue by nelson6e65** [muesli/markscribe#24]
I use other Actions for updating my README file, like [athul/waka-readme](https://github.com/athul/waka-readme) that  [updates my README with Wakatime stats](https://github.com/nelson6e65/nelson6e65/commit/cc701478e9673daae89f42107e8a22df5291e2b7).

This will override my README file instead of just update by sections, like  [athul/waka-readme](https://github.com/athul/waka-readme)?

**Comment by muesli** [comment]
It operates on a template, but will eventually overwrite the README with a newly generated file.
