### ISSUE TITLE
No build and deploy instructions

### ISSUE THREAD

**Issue by guysoft** [muesli/markscribe#3]
Hey,
So as a non-go developer, I had to figure out on my own that:

1. Requirements: You need Go > 1.14 (1.13 fails due to some dependency).
2. You need to get a private github token for your profile from ``top right profile icon>settings>developer options>Personal access tokens``
3. Run using (after cloning and cd in to the repo):
```
GITHUB_TOKEN=xxxxx go run . templates/github-profile.tpl
```

Things I didn't figure out:
1.
There is no info on how to automate this without exposing the github token - any info on how you did that?
2. There is no information on what permissions to give the Personal access token, that would be helpful as input here to.

Would be happy to PR more documentation once I understand if I am using this correctly - and once I have answers to what I didn't figure out.

**Comment by muesli** [comment]
Hey Guy,

thanks for your feedback! Indeed the README is lacking a bit of documentation right now, but I'm working on updating it and explaining things in more detail.

To answer your questions:
1. There's a separate GitHub Action called `readme-scribe`, which you can use to automate the updates. You will have to provide your GITHUB_TOKEN as a secret to it (Repo Settings -> Secrets).
2. Read-only is absolutely sufficient here. I will make the authentication optional, but obviously some API calls will require it (retrieving recently created repositories, for example).

PRs are always welcome and appreciated!

**Comment by muesli** [comment]
I think the basic documentation in master is sufficient now.
