### ISSUE TITLE
Sponsor from org is not processed

### ISSUE THREAD

**Issue by crazy-max** [muesli/markscribe#31]
Hi,

First of all thanks for this lib. I use it through your `readme-scribe` action and it works pretty well except for one thing. If an org sponsors me, the [User entity](https://github.com/crazy-max/crazy-max/blob/f8716d665bf3f08dd6863172a9515885d2f0122b/templates/README.md.tpl#L21) is empty and so displayed as anonymous on my readme.

I think you have to take into account the [Organization object](https://docs.github.com/en/graphql/reference/objects#organization) in the [Sponsor entity](https://docs.github.com/en/graphql/reference/unions#sponsor).

**Comment by muesli** [comment]
I fully blame this bug on no org sponsoring me so far! :laughing: 

In all seriousness tho: thanks for reporting this issue! I'll see what I can do, but it'll probably be hard for me to actually test it. Any help would be appreciated here!

**Comment by crazy-max** [comment]
@muesli 

> Any help would be appreciated here!

I haven't looked at the code yet but if you need to test it don't hesitate to tell me!
