### ISSUE TITLE
[documentation] API scope 

### ISSUE THREAD

**Issue by arthurlutz** [muesli/markscribe#33]
After regenerating the token, I get : 

```
Can't render template: template: tpl:13:8: executing "tpl" at <recentContributions 10>: error calling recentContributions: Something went wrong while executing your query. Please include `0400:54D9:31B115A:5FB5358:60D04DFE` when reporting this issue.
```
I think I messed up the scope of the API token, not giving it enough access. 

![Screenshot from 2021-06-21 10-43-03](https://user-images.githubusercontent.com/108437/122733812-d159cb80-d27d-11eb-829c-764461a9e4f8.png)

What's the minimal API scope that one has to give for `recentContributions` to work ?

**Comment by arthurlutz** [comment]
Seems that changing : 

![Screenshot from 2021-06-21 10-48-37](https://user-images.githubusercontent.com/108437/122734338-46c59c00-d27e-11eb-92fd-556eac5d35ce.png)

Solves the `recentContributions` template.

**Comment by muesli** [comment]
Added some more documentation to the README.
