### ISSUE TITLE
Recent contributions shows only those with commits to the default branch?

### ISSUE THREAD

**Issue by OJFord** [muesli/markscribe#34]
I don't know if this is intended, but it seems that 'recent contributions' doesn't include commits to non-default (e.g. master) branches?

So, if you fork, branch, and open a PR - it doesn't show as a 'contribution' until it's merged, even on your forked repo.

I suppose it makes some sort of sense for 'contributions' to work like that - perhaps the problem is that I was viewing it / trying to use it as just a sort of 'recent activity' (in terms of commits anyway) overview.

**Comment by muesli** [comment]
I think this may be a limitation of GitHub's GraphQL API. Incidentally it also only counts these kind of contributions (on the default branch) as activity on your profile.

**Comment by zifter** [comment]
Let me leave it here:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile
I have the same problem and found that sometimes I'm using  credentials with different emails. So, all my pr made with email which is not equal to email in github account is not showing up on my profile.

**Comment by OJFord** [comment]
Got it, thanks. Shame (it makes contributions and releases quite similar) but nevermind, closing as seems not really addressable here.
