### ISSUE TITLE
Is Star Syntax in README Incorrect?

### ISSUE THREAD

**Issue by dakotahp** [muesli/markscribe#35]
The readme mentions we can do the following to query the starred repos:

```
{{range recentStars 10}}
Name: {{.Name}}
Description: {{.Description}}
URL: {{.URL}})
Stars: {{.Stargazers}}
{{end}}
```

But the internal template file has `.Repo` added before each individual value. https://github.com/muesli/markscribe/pull/25/files#diff-48fcd2f0bdec681f14ab75bd86a8fe3da7f851523d98193380608632a13cbbd7R30

I was not able to get a workflow to run with the README example but it did work once I found the PR and dug into the details to know to add `.Repo`. Is it really incorrect or am I missing something? It would be nice if the example was functional.

**Comment by muesli** [comment]
Sounds like it's incorrectly documented indeed!
